theme: jekyll-theme-hacker
title: OSCP training - Vulnerable VMs writeups
tagline: A blog dedicated to offensive security training
description: A blog dedicated to offensive security training - vulerable VMs writeups
url: https://teogia.github.io/offsec-training/
author: TeoGia
lang: en_US
plugins:
  - jekyll-seo-tag